-- SeusyTV All-in-One WP Migration compatible database export
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
DROP TABLE IF EXISTS `SERVMASK_PREFIX_options`;
CREATE TABLE `SERVMASK_PREFIX_options` (`option_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `option_name` varchar(191) NOT NULL DEFAULT '', `option_value` longtext NOT NULL, `autoload` varchar(20) NOT NULL DEFAULT 'yes', PRIMARY KEY (`option_id`), UNIQUE KEY `option_name` (`option_name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `SERVMASK_PREFIX_options` VALUES (1,'siteurl','https://peru-hamster-515841.hostingersite.com','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (2,'home','https://peru-hamster-515841.hostingersite.com','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (3,'blogname','SeusyTV','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (4,'blogdescription','Premium IPTV streaming for Canada and UK viewers.','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (5,'users_can_register','0','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (6,'admin_email','support@seusytv.com','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (7,'start_of_week','1','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (8,'use_smilies','1','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (9,'require_name_email','1','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (10,'comments_notify','1','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (11,'posts_per_rss','10','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (12,'rss_use_excerpt','0','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (13,'default_category','1','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (14,'default_comment_status','closed','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (15,'default_ping_status','closed','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (16,'posts_per_page','10','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (17,'date_format','F j, Y','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (18,'time_format','g:i a','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (19,'permalink_structure','/%postname%/','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (20,'stylesheet','seusytv-premium','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (21,'template','seusytv-premium','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (22,'current_theme','SeusyTV Premium IPTV','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (23,'active_plugins','a:1:{i:0;s:47:"seusytv-site-importer/seusytv-site-importer.php";}','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (24,'show_on_front','posts','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (25,'seusytv_site_imported','0','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (26,'seusytv_primary_cta_url','/free-trial/','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (27,'seusytv_support_email','support@seusytv.com','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (28,'seusytv_guarantee','7 day satisfaction guarantee','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (29,'seusytv_plan_1_price','CAD $15','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (30,'seusytv_plan_3_price','CAD $35','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (31,'seusytv_plan_6_price','CAD $55','yes');
INSERT INTO `SERVMASK_PREFIX_options` VALUES (32,'seusytv_plan_12_price','CAD $85','yes');
DROP TABLE IF EXISTS `SERVMASK_PREFIX_users`;
CREATE TABLE `SERVMASK_PREFIX_users` (`ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `user_login` varchar(60) NOT NULL DEFAULT '', `user_pass` varchar(255) NOT NULL DEFAULT '', `user_nicename` varchar(50) NOT NULL DEFAULT '', `user_email` varchar(100) NOT NULL DEFAULT '', `user_url` varchar(100) NOT NULL DEFAULT '', `user_registered` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `user_activation_key` varchar(255) NOT NULL DEFAULT '', `user_status` int(11) NOT NULL DEFAULT 0, `display_name` varchar(250) NOT NULL DEFAULT '', PRIMARY KEY (`ID`), KEY `user_login_key` (`user_login`), KEY `user_nicename` (`user_nicename`), KEY `user_email` (`user_email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `SERVMASK_PREFIX_users` VALUES (1,'seusytv-owner','$P$BstvfinalOnZTahFyvzN2.qsazUqh5/','seusytv-owner','support@seusytv.com','https://peru-hamster-515841.hostingersite.com','2026-05-25 18:00:12','',0,'SeusyTV Owner');
DROP TABLE IF EXISTS `SERVMASK_PREFIX_usermeta`;
CREATE TABLE `SERVMASK_PREFIX_usermeta` (`umeta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint(20) unsigned NOT NULL DEFAULT 0, `meta_key` varchar(255) DEFAULT NULL, `meta_value` longtext DEFAULT NULL, PRIMARY KEY (`umeta_id`), KEY `user_id` (`user_id`), KEY `meta_key` (`meta_key`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `SERVMASK_PREFIX_usermeta` VALUES (1,1,'SERVMASK_PREFIX_capabilities','a:1:{s:13:"administrator";b:1;}'),(2,1,'SERVMASK_PREFIX_user_level','10');
DROP TABLE IF EXISTS `SERVMASK_PREFIX_posts`;
CREATE TABLE `SERVMASK_PREFIX_posts` (`ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `post_author` bigint(20) unsigned NOT NULL DEFAULT 0, `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `post_content` longtext NOT NULL, `post_title` text NOT NULL, `post_excerpt` text NOT NULL, `post_status` varchar(20) NOT NULL DEFAULT 'publish', `comment_status` varchar(20) NOT NULL DEFAULT 'open', `ping_status` varchar(20) NOT NULL DEFAULT 'open', `post_password` varchar(255) NOT NULL DEFAULT '', `post_name` varchar(200) NOT NULL DEFAULT '', `to_ping` text NOT NULL, `pinged` text NOT NULL, `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `post_content_filtered` longtext NOT NULL, `post_parent` bigint(20) unsigned NOT NULL DEFAULT 0, `guid` varchar(255) NOT NULL DEFAULT '', `menu_order` int(11) NOT NULL DEFAULT 0, `post_type` varchar(20) NOT NULL DEFAULT 'post', `post_mime_type` varchar(100) NOT NULL DEFAULT '', `comment_count` bigint(20) NOT NULL DEFAULT 0, PRIMARY KEY (`ID`), KEY `post_name` (`post_name`(191)), KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`), KEY `post_parent` (`post_parent`), KEY `post_author` (`post_author`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `SERVMASK_PREFIX_postmeta`;
CREATE TABLE `SERVMASK_PREFIX_postmeta` (`meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `post_id` bigint(20) unsigned NOT NULL DEFAULT 0, `meta_key` varchar(255) DEFAULT NULL, `meta_value` longtext DEFAULT NULL, PRIMARY KEY (`meta_id`), KEY `post_id` (`post_id`), KEY `meta_key` (`meta_key`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `SERVMASK_PREFIX_comments`;
CREATE TABLE `SERVMASK_PREFIX_comments` (`comment_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `comment_post_ID` bigint(20) unsigned NOT NULL DEFAULT 0, `comment_author` tinytext NOT NULL, `comment_author_email` varchar(100) NOT NULL DEFAULT '', `comment_author_url` varchar(200) NOT NULL DEFAULT '', `comment_author_IP` varchar(100) NOT NULL DEFAULT '', `comment_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `comment_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `comment_content` text NOT NULL, `comment_karma` int(11) NOT NULL DEFAULT 0, `comment_approved` varchar(20) NOT NULL DEFAULT '1', `comment_agent` varchar(255) NOT NULL DEFAULT '', `comment_type` varchar(20) NOT NULL DEFAULT 'comment', `comment_parent` bigint(20) unsigned NOT NULL DEFAULT 0, `user_id` bigint(20) unsigned NOT NULL DEFAULT 0, PRIMARY KEY (`comment_ID`), KEY `comment_post_ID` (`comment_post_ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `SERVMASK_PREFIX_commentmeta`;
CREATE TABLE `SERVMASK_PREFIX_commentmeta` (`meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `comment_id` bigint(20) unsigned NOT NULL DEFAULT 0, `meta_key` varchar(255) DEFAULT NULL, `meta_value` longtext DEFAULT NULL, PRIMARY KEY (`meta_id`), KEY `comment_id` (`comment_id`), KEY `meta_key` (`meta_key`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `SERVMASK_PREFIX_terms`;
CREATE TABLE `SERVMASK_PREFIX_terms` (`term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `name` varchar(200) NOT NULL DEFAULT '', `slug` varchar(200) NOT NULL DEFAULT '', `term_group` bigint(10) NOT NULL DEFAULT 0, PRIMARY KEY (`term_id`), KEY `slug` (`slug`(191)), KEY `name` (`name`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `SERVMASK_PREFIX_term_taxonomy`;
CREATE TABLE `SERVMASK_PREFIX_term_taxonomy` (`term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `term_id` bigint(20) unsigned NOT NULL DEFAULT 0, `taxonomy` varchar(32) NOT NULL DEFAULT '', `description` longtext NOT NULL, `parent` bigint(20) unsigned NOT NULL DEFAULT 0, `count` bigint(20) NOT NULL DEFAULT 0, PRIMARY KEY (`term_taxonomy_id`), UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`), KEY `taxonomy` (`taxonomy`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `SERVMASK_PREFIX_term_relationships`;
CREATE TABLE `SERVMASK_PREFIX_term_relationships` (`object_id` bigint(20) unsigned NOT NULL DEFAULT 0, `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT 0, `term_order` int(11) NOT NULL DEFAULT 0, PRIMARY KEY (`object_id`,`term_taxonomy_id`), KEY `term_taxonomy_id` (`term_taxonomy_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `SERVMASK_PREFIX_termmeta`;
CREATE TABLE `SERVMASK_PREFIX_termmeta` (`meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `term_id` bigint(20) unsigned NOT NULL DEFAULT 0, `meta_key` varchar(255) DEFAULT NULL, `meta_value` longtext DEFAULT NULL, PRIMARY KEY (`meta_id`), KEY `term_id` (`term_id`), KEY `meta_key` (`meta_key`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `SERVMASK_PREFIX_links`;
CREATE TABLE `SERVMASK_PREFIX_links` (`link_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `link_url` varchar(255) NOT NULL DEFAULT '', `link_name` varchar(255) NOT NULL DEFAULT '', `link_image` varchar(255) NOT NULL DEFAULT '', `link_target` varchar(25) NOT NULL DEFAULT '', `link_description` varchar(255) NOT NULL DEFAULT '', `link_visible` varchar(20) NOT NULL DEFAULT 'Y', `link_owner` bigint(20) unsigned NOT NULL DEFAULT 1, `link_rating` int(11) NOT NULL DEFAULT 0, `link_updated` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `link_rel` varchar(255) NOT NULL DEFAULT '', `link_notes` mediumtext NOT NULL, `link_rss` varchar(255) NOT NULL DEFAULT '', PRIMARY KEY (`link_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `SERVMASK_PREFIX_terms` VALUES (1,'Uncategorized','uncategorized',0);
INSERT INTO `SERVMASK_PREFIX_term_taxonomy` VALUES (1,1,'category','',0,0);
COMMIT;
